// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: nexusflow.proto
#ifndef GRPC_nexusflow_2eproto__INCLUDED
#define GRPC_nexusflow_2eproto__INCLUDED

#include "nexusflow.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace nexusflow {
namespace grpc {

class NexusFlowService final {
 public:
  static constexpr char const* service_full_name() {
    return "nexusflow.grpc.NexusFlowService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SubmitEvent(::grpc::ClientContext* context, const ::nexusflow::grpc::EventRequest& request, ::nexusflow::grpc::EventResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nexusflow::grpc::EventResponse>> AsyncSubmitEvent(::grpc::ClientContext* context, const ::nexusflow::grpc::EventRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nexusflow::grpc::EventResponse>>(AsyncSubmitEventRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nexusflow::grpc::EventResponse>> PrepareAsyncSubmitEvent(::grpc::ClientContext* context, const ::nexusflow::grpc::EventRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nexusflow::grpc::EventResponse>>(PrepareAsyncSubmitEventRaw(context, request, cq));
    }
    virtual ::grpc::Status Health(::grpc::ClientContext* context, const ::nexusflow::grpc::HealthRequest& request, ::nexusflow::grpc::HealthResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nexusflow::grpc::HealthResponse>> AsyncHealth(::grpc::ClientContext* context, const ::nexusflow::grpc::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nexusflow::grpc::HealthResponse>>(AsyncHealthRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nexusflow::grpc::HealthResponse>> PrepareAsyncHealth(::grpc::ClientContext* context, const ::nexusflow::grpc::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nexusflow::grpc::HealthResponse>>(PrepareAsyncHealthRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SubmitEvent(::grpc::ClientContext* context, const ::nexusflow::grpc::EventRequest* request, ::nexusflow::grpc::EventResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SubmitEvent(::grpc::ClientContext* context, const ::nexusflow::grpc::EventRequest* request, ::nexusflow::grpc::EventResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Health(::grpc::ClientContext* context, const ::nexusflow::grpc::HealthRequest* request, ::nexusflow::grpc::HealthResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Health(::grpc::ClientContext* context, const ::nexusflow::grpc::HealthRequest* request, ::nexusflow::grpc::HealthResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nexusflow::grpc::EventResponse>* AsyncSubmitEventRaw(::grpc::ClientContext* context, const ::nexusflow::grpc::EventRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nexusflow::grpc::EventResponse>* PrepareAsyncSubmitEventRaw(::grpc::ClientContext* context, const ::nexusflow::grpc::EventRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nexusflow::grpc::HealthResponse>* AsyncHealthRaw(::grpc::ClientContext* context, const ::nexusflow::grpc::HealthRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nexusflow::grpc::HealthResponse>* PrepareAsyncHealthRaw(::grpc::ClientContext* context, const ::nexusflow::grpc::HealthRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SubmitEvent(::grpc::ClientContext* context, const ::nexusflow::grpc::EventRequest& request, ::nexusflow::grpc::EventResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nexusflow::grpc::EventResponse>> AsyncSubmitEvent(::grpc::ClientContext* context, const ::nexusflow::grpc::EventRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nexusflow::grpc::EventResponse>>(AsyncSubmitEventRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nexusflow::grpc::EventResponse>> PrepareAsyncSubmitEvent(::grpc::ClientContext* context, const ::nexusflow::grpc::EventRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nexusflow::grpc::EventResponse>>(PrepareAsyncSubmitEventRaw(context, request, cq));
    }
    ::grpc::Status Health(::grpc::ClientContext* context, const ::nexusflow::grpc::HealthRequest& request, ::nexusflow::grpc::HealthResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nexusflow::grpc::HealthResponse>> AsyncHealth(::grpc::ClientContext* context, const ::nexusflow::grpc::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nexusflow::grpc::HealthResponse>>(AsyncHealthRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nexusflow::grpc::HealthResponse>> PrepareAsyncHealth(::grpc::ClientContext* context, const ::nexusflow::grpc::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nexusflow::grpc::HealthResponse>>(PrepareAsyncHealthRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SubmitEvent(::grpc::ClientContext* context, const ::nexusflow::grpc::EventRequest* request, ::nexusflow::grpc::EventResponse* response, std::function<void(::grpc::Status)>) override;
      void SubmitEvent(::grpc::ClientContext* context, const ::nexusflow::grpc::EventRequest* request, ::nexusflow::grpc::EventResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Health(::grpc::ClientContext* context, const ::nexusflow::grpc::HealthRequest* request, ::nexusflow::grpc::HealthResponse* response, std::function<void(::grpc::Status)>) override;
      void Health(::grpc::ClientContext* context, const ::nexusflow::grpc::HealthRequest* request, ::nexusflow::grpc::HealthResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::nexusflow::grpc::EventResponse>* AsyncSubmitEventRaw(::grpc::ClientContext* context, const ::nexusflow::grpc::EventRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::nexusflow::grpc::EventResponse>* PrepareAsyncSubmitEventRaw(::grpc::ClientContext* context, const ::nexusflow::grpc::EventRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::nexusflow::grpc::HealthResponse>* AsyncHealthRaw(::grpc::ClientContext* context, const ::nexusflow::grpc::HealthRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::nexusflow::grpc::HealthResponse>* PrepareAsyncHealthRaw(::grpc::ClientContext* context, const ::nexusflow::grpc::HealthRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SubmitEvent_;
    const ::grpc::internal::RpcMethod rpcmethod_Health_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SubmitEvent(::grpc::ServerContext* context, const ::nexusflow::grpc::EventRequest* request, ::nexusflow::grpc::EventResponse* response);
    virtual ::grpc::Status Health(::grpc::ServerContext* context, const ::nexusflow::grpc::HealthRequest* request, ::nexusflow::grpc::HealthResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SubmitEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SubmitEvent() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SubmitEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitEvent(::grpc::ServerContext* /*context*/, const ::nexusflow::grpc::EventRequest* /*request*/, ::nexusflow::grpc::EventResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubmitEvent(::grpc::ServerContext* context, ::nexusflow::grpc::EventRequest* request, ::grpc::ServerAsyncResponseWriter< ::nexusflow::grpc::EventResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Health() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::nexusflow::grpc::HealthRequest* /*request*/, ::nexusflow::grpc::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHealth(::grpc::ServerContext* context, ::nexusflow::grpc::HealthRequest* request, ::grpc::ServerAsyncResponseWriter< ::nexusflow::grpc::HealthResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SubmitEvent<WithAsyncMethod_Health<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SubmitEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SubmitEvent() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::nexusflow::grpc::EventRequest, ::nexusflow::grpc::EventResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::nexusflow::grpc::EventRequest* request, ::nexusflow::grpc::EventResponse* response) { return this->SubmitEvent(context, request, response); }));}
    void SetMessageAllocatorFor_SubmitEvent(
        ::grpc::MessageAllocator< ::nexusflow::grpc::EventRequest, ::nexusflow::grpc::EventResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::nexusflow::grpc::EventRequest, ::nexusflow::grpc::EventResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SubmitEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitEvent(::grpc::ServerContext* /*context*/, const ::nexusflow::grpc::EventRequest* /*request*/, ::nexusflow::grpc::EventResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SubmitEvent(
      ::grpc::CallbackServerContext* /*context*/, const ::nexusflow::grpc::EventRequest* /*request*/, ::nexusflow::grpc::EventResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Health() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::nexusflow::grpc::HealthRequest, ::nexusflow::grpc::HealthResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::nexusflow::grpc::HealthRequest* request, ::nexusflow::grpc::HealthResponse* response) { return this->Health(context, request, response); }));}
    void SetMessageAllocatorFor_Health(
        ::grpc::MessageAllocator< ::nexusflow::grpc::HealthRequest, ::nexusflow::grpc::HealthResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::nexusflow::grpc::HealthRequest, ::nexusflow::grpc::HealthResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::nexusflow::grpc::HealthRequest* /*request*/, ::nexusflow::grpc::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Health(
      ::grpc::CallbackServerContext* /*context*/, const ::nexusflow::grpc::HealthRequest* /*request*/, ::nexusflow::grpc::HealthResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SubmitEvent<WithCallbackMethod_Health<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SubmitEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SubmitEvent() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SubmitEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitEvent(::grpc::ServerContext* /*context*/, const ::nexusflow::grpc::EventRequest* /*request*/, ::nexusflow::grpc::EventResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Health() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::nexusflow::grpc::HealthRequest* /*request*/, ::nexusflow::grpc::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SubmitEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SubmitEvent() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SubmitEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitEvent(::grpc::ServerContext* /*context*/, const ::nexusflow::grpc::EventRequest* /*request*/, ::nexusflow::grpc::EventResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubmitEvent(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Health() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::nexusflow::grpc::HealthRequest* /*request*/, ::nexusflow::grpc::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHealth(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SubmitEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SubmitEvent() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SubmitEvent(context, request, response); }));
    }
    ~WithRawCallbackMethod_SubmitEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitEvent(::grpc::ServerContext* /*context*/, const ::nexusflow::grpc::EventRequest* /*request*/, ::nexusflow::grpc::EventResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SubmitEvent(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Health() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Health(context, request, response); }));
    }
    ~WithRawCallbackMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::nexusflow::grpc::HealthRequest* /*request*/, ::nexusflow::grpc::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Health(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SubmitEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SubmitEvent() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::nexusflow::grpc::EventRequest, ::nexusflow::grpc::EventResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::nexusflow::grpc::EventRequest, ::nexusflow::grpc::EventResponse>* streamer) {
                       return this->StreamedSubmitEvent(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SubmitEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SubmitEvent(::grpc::ServerContext* /*context*/, const ::nexusflow::grpc::EventRequest* /*request*/, ::nexusflow::grpc::EventResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSubmitEvent(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::nexusflow::grpc::EventRequest,::nexusflow::grpc::EventResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Health() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::nexusflow::grpc::HealthRequest, ::nexusflow::grpc::HealthResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::nexusflow::grpc::HealthRequest, ::nexusflow::grpc::HealthResponse>* streamer) {
                       return this->StreamedHealth(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::nexusflow::grpc::HealthRequest* /*request*/, ::nexusflow::grpc::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedHealth(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::nexusflow::grpc::HealthRequest,::nexusflow::grpc::HealthResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SubmitEvent<WithStreamedUnaryMethod_Health<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SubmitEvent<WithStreamedUnaryMethod_Health<Service > > StreamedService;
};

}  // namespace grpc
}  // namespace nexusflow


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_nexusflow_2eproto__INCLUDED
