// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nexusflow.proto
// Protobuf C++ Version: 5.29.3

#include "nexusflow.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace nexusflow {
namespace grpc {

inline constexpr HealthResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : processed_events_{::uint64_t{0u}},
        healthy_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR HealthResponse::HealthResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct HealthResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HealthResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HealthResponseDefaultTypeInternal() {}
  union {
    HealthResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HealthResponseDefaultTypeInternal _HealthResponse_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR HealthRequest::HealthRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct HealthRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HealthRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HealthRequestDefaultTypeInternal() {}
  union {
    HealthRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HealthRequestDefaultTypeInternal _HealthRequest_default_instance_;

inline constexpr EventResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        accepted_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR EventResponse::EventResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EventResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EventResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EventResponseDefaultTypeInternal() {}
  union {
    EventResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EventResponseDefaultTypeInternal _EventResponse_default_instance_;

inline constexpr EventRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : payload_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        event_id_{::uint64_t{0u}},
        timestamp_ms_{::uint64_t{0u}},
        type_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR EventRequest::EventRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EventRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EventRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EventRequestDefaultTypeInternal() {}
  union {
    EventRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EventRequestDefaultTypeInternal _EventRequest_default_instance_;
}  // namespace grpc
}  // namespace nexusflow
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_nexusflow_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_nexusflow_2eproto = nullptr;
const ::uint32_t
    TableStruct_nexusflow_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::nexusflow::grpc::EventRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::nexusflow::grpc::EventRequest, _impl_.event_id_),
        PROTOBUF_FIELD_OFFSET(::nexusflow::grpc::EventRequest, _impl_.timestamp_ms_),
        PROTOBUF_FIELD_OFFSET(::nexusflow::grpc::EventRequest, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::nexusflow::grpc::EventRequest, _impl_.payload_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::nexusflow::grpc::EventResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::nexusflow::grpc::EventResponse, _impl_.accepted_),
        PROTOBUF_FIELD_OFFSET(::nexusflow::grpc::EventResponse, _impl_.message_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::nexusflow::grpc::HealthRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::nexusflow::grpc::HealthResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::nexusflow::grpc::HealthResponse, _impl_.healthy_),
        PROTOBUF_FIELD_OFFSET(::nexusflow::grpc::HealthResponse, _impl_.processed_events_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::nexusflow::grpc::EventRequest)},
        {12, -1, -1, sizeof(::nexusflow::grpc::EventResponse)},
        {22, -1, -1, sizeof(::nexusflow::grpc::HealthRequest)},
        {30, -1, -1, sizeof(::nexusflow::grpc::HealthResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::nexusflow::grpc::_EventRequest_default_instance_._instance,
    &::nexusflow::grpc::_EventResponse_default_instance_._instance,
    &::nexusflow::grpc::_HealthRequest_default_instance_._instance,
    &::nexusflow::grpc::_HealthResponse_default_instance_._instance,
};
const char descriptor_table_protodef_nexusflow_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017nexusflow.proto\022\016nexusflow.grpc\"U\n\014Eve"
    "ntRequest\022\020\n\010event_id\030\001 \001(\004\022\024\n\014timestamp"
    "_ms\030\002 \001(\004\022\014\n\004type\030\003 \001(\r\022\017\n\007payload\030\004 \001(\t"
    "\"2\n\rEventResponse\022\020\n\010accepted\030\001 \001(\010\022\017\n\007m"
    "essage\030\002 \001(\t\"\017\n\rHealthRequest\";\n\016HealthR"
    "esponse\022\017\n\007healthy\030\001 \001(\010\022\030\n\020processed_ev"
    "ents\030\002 \001(\0042\247\001\n\020NexusFlowService\022J\n\013Submi"
    "tEvent\022\034.nexusflow.grpc.EventRequest\032\035.n"
    "exusflow.grpc.EventResponse\022G\n\006Health\022\035."
    "nexusflow.grpc.HealthRequest\032\036.nexusflow"
    ".grpc.HealthResponseb\006proto3"
};
static ::absl::once_flag descriptor_table_nexusflow_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_nexusflow_2eproto = {
    false,
    false,
    428,
    descriptor_table_protodef_nexusflow_2eproto,
    "nexusflow.proto",
    &descriptor_table_nexusflow_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_nexusflow_2eproto::offsets,
    file_level_enum_descriptors_nexusflow_2eproto,
    file_level_service_descriptors_nexusflow_2eproto,
};
namespace nexusflow {
namespace grpc {
// ===================================================================

class EventRequest::_Internal {
 public:
};

EventRequest::EventRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:nexusflow.grpc.EventRequest)
}
inline PROTOBUF_NDEBUG_INLINE EventRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::nexusflow::grpc::EventRequest& from_msg)
      : payload_(arena, from.payload_),
        _cached_size_{0} {}

EventRequest::EventRequest(
    ::google::protobuf::Arena* arena,
    const EventRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  EventRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, event_id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, event_id_),
           offsetof(Impl_, type_) -
               offsetof(Impl_, event_id_) +
               sizeof(Impl_::type_));

  // @@protoc_insertion_point(copy_constructor:nexusflow.grpc.EventRequest)
}
inline PROTOBUF_NDEBUG_INLINE EventRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : payload_(arena),
        _cached_size_{0} {}

inline void EventRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, event_id_),
           0,
           offsetof(Impl_, type_) -
               offsetof(Impl_, event_id_) +
               sizeof(Impl_::type_));
}
EventRequest::~EventRequest() {
  // @@protoc_insertion_point(destructor:nexusflow.grpc.EventRequest)
  SharedDtor(*this);
}
inline void EventRequest::SharedDtor(MessageLite& self) {
  EventRequest& this_ = static_cast<EventRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.payload_.Destroy();
  this_._impl_.~Impl_();
}

inline void* EventRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) EventRequest(arena);
}
constexpr auto EventRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(EventRequest),
                                            alignof(EventRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull EventRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_EventRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &EventRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<EventRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &EventRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<EventRequest>(), &EventRequest::ByteSizeLong,
            &EventRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(EventRequest, _impl_._cached_size_),
        false,
    },
    &EventRequest::kDescriptorMethods,
    &descriptor_table_nexusflow_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* EventRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 43, 2> EventRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nexusflow::grpc::EventRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string payload = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(EventRequest, _impl_.payload_)}},
    // uint64 event_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(EventRequest, _impl_.event_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(EventRequest, _impl_.event_id_)}},
    // uint64 timestamp_ms = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(EventRequest, _impl_.timestamp_ms_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(EventRequest, _impl_.timestamp_ms_)}},
    // uint32 type = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(EventRequest, _impl_.type_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(EventRequest, _impl_.type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 event_id = 1;
    {PROTOBUF_FIELD_OFFSET(EventRequest, _impl_.event_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint64 timestamp_ms = 2;
    {PROTOBUF_FIELD_OFFSET(EventRequest, _impl_.timestamp_ms_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint32 type = 3;
    {PROTOBUF_FIELD_OFFSET(EventRequest, _impl_.type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // string payload = 4;
    {PROTOBUF_FIELD_OFFSET(EventRequest, _impl_.payload_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\33\0\0\0\7\0\0\0"
    "nexusflow.grpc.EventRequest"
    "payload"
  }},
};

PROTOBUF_NOINLINE void EventRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:nexusflow.grpc.EventRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.payload_.ClearToEmpty();
  ::memset(&_impl_.event_id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.type_) -
      reinterpret_cast<char*>(&_impl_.event_id_)) + sizeof(_impl_.type_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* EventRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const EventRequest& this_ = static_cast<const EventRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* EventRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const EventRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:nexusflow.grpc.EventRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint64 event_id = 1;
          if (this_._internal_event_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                1, this_._internal_event_id(), target);
          }

          // uint64 timestamp_ms = 2;
          if (this_._internal_timestamp_ms() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                2, this_._internal_timestamp_ms(), target);
          }

          // uint32 type = 3;
          if (this_._internal_type() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                3, this_._internal_type(), target);
          }

          // string payload = 4;
          if (!this_._internal_payload().empty()) {
            const std::string& _s = this_._internal_payload();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nexusflow.grpc.EventRequest.payload");
            target = stream->WriteStringMaybeAliased(4, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:nexusflow.grpc.EventRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t EventRequest::ByteSizeLong(const MessageLite& base) {
          const EventRequest& this_ = static_cast<const EventRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t EventRequest::ByteSizeLong() const {
          const EventRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:nexusflow.grpc.EventRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string payload = 4;
            if (!this_._internal_payload().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_payload());
            }
            // uint64 event_id = 1;
            if (this_._internal_event_id() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_event_id());
            }
            // uint64 timestamp_ms = 2;
            if (this_._internal_timestamp_ms() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_timestamp_ms());
            }
            // uint32 type = 3;
            if (this_._internal_type() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_type());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void EventRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<EventRequest*>(&to_msg);
  auto& from = static_cast<const EventRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:nexusflow.grpc.EventRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_payload().empty()) {
    _this->_internal_set_payload(from._internal_payload());
  }
  if (from._internal_event_id() != 0) {
    _this->_impl_.event_id_ = from._impl_.event_id_;
  }
  if (from._internal_timestamp_ms() != 0) {
    _this->_impl_.timestamp_ms_ = from._impl_.timestamp_ms_;
  }
  if (from._internal_type() != 0) {
    _this->_impl_.type_ = from._impl_.type_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void EventRequest::CopyFrom(const EventRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nexusflow.grpc.EventRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void EventRequest::InternalSwap(EventRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.payload_, &other->_impl_.payload_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(EventRequest, _impl_.type_)
      + sizeof(EventRequest::_impl_.type_)
      - PROTOBUF_FIELD_OFFSET(EventRequest, _impl_.event_id_)>(
          reinterpret_cast<char*>(&_impl_.event_id_),
          reinterpret_cast<char*>(&other->_impl_.event_id_));
}

::google::protobuf::Metadata EventRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class EventResponse::_Internal {
 public:
};

EventResponse::EventResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:nexusflow.grpc.EventResponse)
}
inline PROTOBUF_NDEBUG_INLINE EventResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::nexusflow::grpc::EventResponse& from_msg)
      : message_(arena, from.message_),
        _cached_size_{0} {}

EventResponse::EventResponse(
    ::google::protobuf::Arena* arena,
    const EventResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  EventResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.accepted_ = from._impl_.accepted_;

  // @@protoc_insertion_point(copy_constructor:nexusflow.grpc.EventResponse)
}
inline PROTOBUF_NDEBUG_INLINE EventResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void EventResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.accepted_ = {};
}
EventResponse::~EventResponse() {
  // @@protoc_insertion_point(destructor:nexusflow.grpc.EventResponse)
  SharedDtor(*this);
}
inline void EventResponse::SharedDtor(MessageLite& self) {
  EventResponse& this_ = static_cast<EventResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_.Destroy();
  this_._impl_.~Impl_();
}

inline void* EventResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) EventResponse(arena);
}
constexpr auto EventResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(EventResponse),
                                            alignof(EventResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull EventResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_EventResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &EventResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<EventResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &EventResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<EventResponse>(), &EventResponse::ByteSizeLong,
            &EventResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(EventResponse, _impl_._cached_size_),
        false,
    },
    &EventResponse::kDescriptorMethods,
    &descriptor_table_nexusflow_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* EventResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 44, 2> EventResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nexusflow::grpc::EventResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string message = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(EventResponse, _impl_.message_)}},
    // bool accepted = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(EventResponse, _impl_.accepted_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(EventResponse, _impl_.accepted_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool accepted = 1;
    {PROTOBUF_FIELD_OFFSET(EventResponse, _impl_.accepted_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // string message = 2;
    {PROTOBUF_FIELD_OFFSET(EventResponse, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\34\0\7\0\0\0\0\0"
    "nexusflow.grpc.EventResponse"
    "message"
  }},
};

PROTOBUF_NOINLINE void EventResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:nexusflow.grpc.EventResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.accepted_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* EventResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const EventResponse& this_ = static_cast<const EventResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* EventResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const EventResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:nexusflow.grpc.EventResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bool accepted = 1;
          if (this_._internal_accepted() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_accepted(), target);
          }

          // string message = 2;
          if (!this_._internal_message().empty()) {
            const std::string& _s = this_._internal_message();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nexusflow.grpc.EventResponse.message");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:nexusflow.grpc.EventResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t EventResponse::ByteSizeLong(const MessageLite& base) {
          const EventResponse& this_ = static_cast<const EventResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t EventResponse::ByteSizeLong() const {
          const EventResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:nexusflow.grpc.EventResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string message = 2;
            if (!this_._internal_message().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_message());
            }
            // bool accepted = 1;
            if (this_._internal_accepted() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void EventResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<EventResponse*>(&to_msg);
  auto& from = static_cast<const EventResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:nexusflow.grpc.EventResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_accepted() != 0) {
    _this->_impl_.accepted_ = from._impl_.accepted_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void EventResponse::CopyFrom(const EventResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nexusflow.grpc.EventResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void EventResponse::InternalSwap(EventResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
        swap(_impl_.accepted_, other->_impl_.accepted_);
}

::google::protobuf::Metadata EventResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class HealthRequest::_Internal {
 public:
};

HealthRequest::HealthRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:nexusflow.grpc.HealthRequest)
}
HealthRequest::HealthRequest(
    ::google::protobuf::Arena* arena,
    const HealthRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  HealthRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:nexusflow.grpc.HealthRequest)
}

inline void* HealthRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) HealthRequest(arena);
}
constexpr auto HealthRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(HealthRequest),
                                            alignof(HealthRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull HealthRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_HealthRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &HealthRequest::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<HealthRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &HealthRequest::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<HealthRequest>(), &HealthRequest::ByteSizeLong,
            &HealthRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(HealthRequest, _impl_._cached_size_),
        false,
    },
    &HealthRequest::kDescriptorMethods,
    &descriptor_table_nexusflow_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* HealthRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> HealthRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nexusflow::grpc::HealthRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata HealthRequest::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class HealthResponse::_Internal {
 public:
};

HealthResponse::HealthResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:nexusflow.grpc.HealthResponse)
}
HealthResponse::HealthResponse(
    ::google::protobuf::Arena* arena, const HealthResponse& from)
    : HealthResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE HealthResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void HealthResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, processed_events_),
           0,
           offsetof(Impl_, healthy_) -
               offsetof(Impl_, processed_events_) +
               sizeof(Impl_::healthy_));
}
HealthResponse::~HealthResponse() {
  // @@protoc_insertion_point(destructor:nexusflow.grpc.HealthResponse)
  SharedDtor(*this);
}
inline void HealthResponse::SharedDtor(MessageLite& self) {
  HealthResponse& this_ = static_cast<HealthResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* HealthResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) HealthResponse(arena);
}
constexpr auto HealthResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(HealthResponse),
                                            alignof(HealthResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull HealthResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_HealthResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &HealthResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<HealthResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &HealthResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<HealthResponse>(), &HealthResponse::ByteSizeLong,
            &HealthResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(HealthResponse, _impl_._cached_size_),
        false,
    },
    &HealthResponse::kDescriptorMethods,
    &descriptor_table_nexusflow_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* HealthResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> HealthResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nexusflow::grpc::HealthResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint64 processed_events = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(HealthResponse, _impl_.processed_events_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(HealthResponse, _impl_.processed_events_)}},
    // bool healthy = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(HealthResponse, _impl_.healthy_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(HealthResponse, _impl_.healthy_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool healthy = 1;
    {PROTOBUF_FIELD_OFFSET(HealthResponse, _impl_.healthy_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // uint64 processed_events = 2;
    {PROTOBUF_FIELD_OFFSET(HealthResponse, _impl_.processed_events_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void HealthResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:nexusflow.grpc.HealthResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.processed_events_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.healthy_) -
      reinterpret_cast<char*>(&_impl_.processed_events_)) + sizeof(_impl_.healthy_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* HealthResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const HealthResponse& this_ = static_cast<const HealthResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* HealthResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const HealthResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:nexusflow.grpc.HealthResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bool healthy = 1;
          if (this_._internal_healthy() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_healthy(), target);
          }

          // uint64 processed_events = 2;
          if (this_._internal_processed_events() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                2, this_._internal_processed_events(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:nexusflow.grpc.HealthResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t HealthResponse::ByteSizeLong(const MessageLite& base) {
          const HealthResponse& this_ = static_cast<const HealthResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t HealthResponse::ByteSizeLong() const {
          const HealthResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:nexusflow.grpc.HealthResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // uint64 processed_events = 2;
            if (this_._internal_processed_events() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_processed_events());
            }
            // bool healthy = 1;
            if (this_._internal_healthy() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void HealthResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<HealthResponse*>(&to_msg);
  auto& from = static_cast<const HealthResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:nexusflow.grpc.HealthResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_processed_events() != 0) {
    _this->_impl_.processed_events_ = from._impl_.processed_events_;
  }
  if (from._internal_healthy() != 0) {
    _this->_impl_.healthy_ = from._impl_.healthy_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void HealthResponse::CopyFrom(const HealthResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nexusflow.grpc.HealthResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void HealthResponse::InternalSwap(HealthResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(HealthResponse, _impl_.healthy_)
      + sizeof(HealthResponse::_impl_.healthy_)
      - PROTOBUF_FIELD_OFFSET(HealthResponse, _impl_.processed_events_)>(
          reinterpret_cast<char*>(&_impl_.processed_events_),
          reinterpret_cast<char*>(&other->_impl_.processed_events_));
}

::google::protobuf::Metadata HealthResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace grpc
}  // namespace nexusflow
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_nexusflow_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
