apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nexusflow
  namespace: nexusflow
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: nexusflow

  policyTypes:
    - Ingress
    - Egress

  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: nexusflow
      ports:
        - protocol: TCP
          port: 8080

  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: nexusflow

  # DNS access
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
